### ISSUE TITLE
Confusingly large number of changes

### ISSUE THREAD

**Issue by sonyps5201314** [microsoft/Detours#183]
In [PR175](https://github.com/microsoft/Detours/pull/175), In many `DETOUR_TRACE `calls related to `GetLastError()`, the formatting parameter `%d` is replaced with `%lx`, but from the `WinError.h` file of the Windows SDK, we can know that these error values ​​are all decimal numbers, so using `%u` will make the code It's easier to understand, and `%lx` hexadecimal will confuse users.
original code:
```c++
        DETOUR_TRACE(("... failed: %d\n", GetLastError()));
```
error code in Windows SDK:
```c++
#define ERROR_INVALID_PARAMETER          87L    // dderror
```

**Comment by sylveon** [comment]
This is because `GetLastError` returns a `DWORD`, which is an `unsigned long`. `%d` or `%u` are not correct, since they're for `int`, and the compiler rightfully complained (even if in MSVC both are 32 bits) and told I should prefer `%lx`. In hindsight, I should have probably used `%lu`, but C format strings are awful and I forgot that `%lu` was a thing :)

I'll write a PR

**Comment by sonyps5201314** [comment]
@sylveon
Thanks for the new PR.
