### ISSUE TITLE
Bug in findfunc\extend.cpp

### ISSUE THREAD

**Issue by GladYouLikeIt** [microsoft/Detours#2]
Extend.cpp is built into extend64.dll for x64, and extend86.dll for x86, but the code in extend.cpp references the dll without specifying the DETOURS_BITS in the dll name. The DetourFindFunction fails because of this.

static int WINAPI ExtendEntryPoint()
{
...
    TrueTarget = (DWORD (WINAPI *)(DWORD)) DetourFindFunction("**target.dll**", "Target");
...
    TrueHidden = (DWORD (WINAPI *)(DWORD)) DetourFindFunction("**target.dll**", "Hidden");
...
}

The 2 places should be changed to use the DETOURS_BITS as follows

    TrueTarget = (DWORD (WINAPI *)(DWORD)) DetourFindFunction("target" **DETOURS_STRINGIFY(DETOURS_BITS)** ".dll", "Target");

    TrueHidden = (DWORD (WINAPI *)(DWORD)) DetourFindFunction("target" **DETOURS_STRINGIFY(DETOURS_BITS)**  ".dll", "Hidden");

**Comment by ohuseyinoglu** [comment]
Same issue exists in SymTest.cpp too - the DLL name ("target.dll") is specified in a hard coded fashion in there as well.

Additionally, (even thoug a copy of it seems to be supplied in the package), the "dbghelp.dll" could be loaded from system path instead of the local path, and that makes hard-coding size of `IMAGEHLP_MODULE64` (at [line 286](https://github.com/microsoft/Detours/blob/master/samples/findfunc/symtest.cpp#L286) as of this comment) buggy, since the API then returns `ERROR_INVALID_PARAMETER` if the struct size doesn't match the in-use binary.
