### ISSUE TITLE
Is it safety to use Detours in running app?

### ISSUE THREAD

**Issue by kostinio** [microsoft/Detours#76]
Intercepted function can be executed while I'm doing my DetourAttach(). Can it lead to process crash or it handled correctly within Detours or it doesn't matter? Is there any other problems? Is it generally safety to use Detours in DLLMain() like this: https://github.com/Microsoft/Detours/wiki/Using-Detours ?

**Comment by sylveon** [comment]
Add threads to the transaction by using `DetourUpdateThread` before calling `DetourAttach`. This will suspend them and resume them once the transaction is committed.

**Comment by kostinio** [comment]
But what if `DetourUpdateThread` will suspend thread inside function which i'm going to intercept? Can calling thread continue executing of original function after resume and return from it correctly?

**Comment by sylveon** [comment]
I suppose that yes since either code execution will either stop right before the trampoline (the call will be correctly detoured once execution resumes) or somewhere after the trampoline (the call will correctly finish and all future calls will be detoured).

I've been using Detours in multithreaded situations and haven't encountered such a concurrency issue yet.

**Comment by kostinio** [comment]
Ok, it really works fine.
