### ISSUE TITLE
DetourCopyInstruction w/o relocation info?

### ISSUE THREAD

**Issue by 0xeb** [microsoft/Detours#95]
Hello,

Imagine the case:

```
F1:
mov rbp, 0x401000
F1_1:
mov rax, 1
call rbp
```

If this `F1` is to be relocated (as part of the trampoline), will DetourCopyInstruction() know to relocate the first instruction?

```
F1:
jmp Hook

F1_Trampoline:
mov rbp, 0x401000
jmp F1_1
```

Normally, this `mov rbp, 0x401000` might or might not have `.reloc` info (based on how the code of F1 is generated (from regular compiler code or jitted code).

Please advise.

**Comment by jaykrell** [comment]
Detours does relocate instructions, when they are RIP relative.
Here:
https://github.com/microsoft/Detours/blob/64ec135a509884aa60ac6c19b59564f1da9cb2fa/src/disasm.cpp#L428

But I don't think it does what you want here, because it does not know if a non-RIP relative instruction had a relocation applied to it by the loader.
It is fairly easy to test this sort of thing out though.

**Comment by 0xeb** [comment]
Thanks
